### ISSUE TITLE
Windows con USB no funciona, pero si con Serial

### ISSUE THREAD

**Issue by csrocha** [csrocha/fpoc-chrome#3]
Si se conecta la impresora por USB la impresora no se reconoce en Windows. Diferente si se conecta desde Serial o un conversor Serial-USB.

La razón parece ser que al instalar la impresora desde USB en Windows, éste no reconoce el dispositivo y no lo publica. Es por ello que Chrome no la reconoce.

**Comment by csrocha** [comment]
Bien, lo hice funcionar usando [Zadig](http://zadig.akeo.ie/) . Permite seleccionar entre tres drivers:
- WinUSB
- libusb-win32/libusb0.sys
- libusbK

Me funcionó con WinUSB luego de reiniciar.

**Comment by martinfpas** [comment]
Consulta, que versión de windows usaste?

**Comment by csrocha** [comment]
@martinfpas , buena tu observación :+1: ( :-1:  lo mio) Utilicé Windows 7 Professional, Service Pack 1 . Y Zadig 2.1.1 para Windows Vista o superior, asociando la impresora al driver WinUSB.

**Comment by maxianastasio** [comment]
Al internar instalar una impresora hasar smh/p-441f por medio de USB a un windows 7 ultimate de 32 bits la misma no es detectada por el el chrome.
