### ISSUE TITLE
No detecta la impresora hasar en windows 7 por usb

### ISSUE THREAD

**Issue by maxianastasio** [csrocha/fpoc-chrome#5]
Al internar instalar una impresora hasar smh/p-441f por medio de USB a un windows 7 ultimate de 32 bits la misma no es detectada por el el chrome.

**Comment by csrocha** [comment]
Maximiliano, necesito el ID USB de la impresora.

En windows vas a tener que ir al dispositivo (usando el administrador de dispositivo) darme los valores idVendor y idProduct que muestra en propiedades.

**Comment by maxianastasio** [comment]
Adjunto la captura donde figura el IdVendor y el IdProduct

![hasar](https://cloud.githubusercontent.com/assets/7604747/5707861/fc92b1ce-9a6a-11e4-8e7c-92e8af2458d8.png)

Cualquier cosa avisame.

Gracias

**Comment by csrocha** [comment]
Maxi, podrías revisar si ahora reconoce la impresora? Solo reconoce, el protocolo que podría usar es el EPSON (Revisión D). Si es así, deberías de verla, nada más. Si es así, podrías adjuntar la captura de la pantalla de la aplicación chrome FPOC?

**Comment by csrocha** [comment]
Ese dispositivo, el 0403:6001 es un conversor SERIAL a USB. Por lo tanto, se presenta en cualquier equipo como Serial y no como una impresora. Caso contrario ocurre con los dispositivos EPSON. Por lo tanto hay que usar la lógica Serial y no usar Zadig para declarar el mismo.

http://www.ftdichip.com/Products/ICs/FT232R.htm

**Comment by maxianastasio** [comment]
Cristian,
             Eso significa que si o si debe conectar el equipo mediante el puerto SR232?

**Comment by csrocha** [comment]
No Maximiliano,

Significa que a pesar de ser una impresora USB, Windows lo reconoce como
puerto Serial. No hay que hacer nada, ni instalar driver. El FPOC lo
debería reconocer automáticamente. El problema es que el protocolo todavía
no está implementado. Lo voy a hacer durante el fin de semana.

Saludos,
Cristian.

2015-01-15 10:57 GMT-03:00 Maximiliano Anastasio notifications@github.com:

> Cristian,
> Eso significa que si o si debe conectar el equipo mediante el puerto SR232?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/csrocha/fpoc-chrome/issues/5#issuecomment-70088552.

## 

Coop. de Trab. Moldeo Interactive Lmt.
Cristian Sebastian Rocha
Consultor Analista.
Bonpland 2363 Of 303
(C1425FWE) CABA, Argentina.
(+54-9-11).6800.0269
http://interactive.moldeo.coop

**Comment by csrocha** [comment]
@maxianastasio, hay una primera versión del protocolo. Quieres intentar probarlo?
