### ISSUE TITLE
Soporte para Bixolon y Tally Dascom

### ISSUE THREAD

**Issue by aek** [csrocha/fpoc-chrome#7]
Seria bueno implementar soporte para las impresoras Bixolon y Tally Dascom. 
De la Bixolon SRP-350 estoy haciendo investigaciones de implementaciones en Python y si llego a algun resultado les puedo contribuir con el codigo necesario. Quisiera saber si existe algun desarrollo en el plugin ya para esto.

**Comment by csrocha** [comment]
Hola @aek , no conozco esas impresoras. Si tienes documentación podría ser viable. Son nuevas en el mercado argentino?

**Comment by aek** [comment]
Hola Cristian, le adjunto el manual que tengo del tema, segun tengo entendido son impresoras fiscales que funcionan mayormente en panama y venezuela, tienen una implementacion de driver que provee The Factory HKA. No pude adjuntarlo aqui por falta de permisos asi que lo colgue en esta url:
http://filesftp.soltein.org/files/Manual%20de%20Protocolos%20y%20Comandos%20(%20V.%205.00)-3.pdf
El tema parece ser que no es exactamente todo lo que dice ahi, cambian algunos codigos, por ejemplo yo en la que implemente para panama para poner la cedula o ruc del cliente uso una linea como esta:
jR*Cédula: 7.543.365

pero en el manual viene como:
iR*Cédula: 7.543.365

Detalles asi pueden variar de una version a otra al parecer o sera la version del driver o algo asi, aunque todos esos comandos tienen representacion de codigos a enviar a la impresora directamente para implementar un driver como los de epson que ya soporta fpoc.
Desconozco si estan funcionando en argentina este tipo de impresoras fiscales.

**Comment by csrocha** [comment]
@aek , gracias por el link. Te voy a dar una mano si te interesa.

Esta código corresponde a la versión E de Argentina de Epson. (https://github.com/csrocha/fpoc-chrome/blob/master/src/epson_e_ar.js)

Deberías crear un archivo src/hka_V_P.js donde V es la versión del protocolo y P es el código [ISO-3166-1 alfa-2](https://es.wikipedia.org/wiki/ISO_3166-1#Tabla_de_c.C3.B3digos_alfa-2_asignados_o_reservados)

En el deberías tener toda la lógica de comandos para el control del dispositivo. El control por usb o serial lo asocia **devices.js**. Deberías crear una entrada para USB y otra para SERIAL si es que lo soporta.

Los comandos que tenés que implementar los podés ver en **sevents.js** . Por ejemplo, el evento "short_test" 

```
    'short_test': function(session, event_id, event_data, printers, callback) {
        console.debug("[EVENT] Short test.");
        var printer_id = event_data.name;
        if (typeof printers == 'object' && printer_id in printers) {
            var printer = printers[printer_id];
            printer.short_test(function(res){ session.send({'event_id': event_id, 'printer_id': printer_id}, callback); });
        }
    }
```

llama a **printer.short_test**. Esta función debería estar declarada en tu archivo de protocolo donde envía los mensajes al dispositivo.

Espero que esto ayude.

**Comment by aek** [comment]
Gracias pero como le comentaba ya resolvi el tema creando una version del plugin que se comunica con un utilitario de tfhka a traves de un script python que se consume utilizando el Messaging Native API de chrome porque no tuve el manual hasta que puse el sistema en produccion, solo tenia el utilitario

**Comment by csrocha** [comment]
Ok! Cierro el issue entonces, por haberlo resuelto de otra forma.

**Comment by alej356** [comment]
Buenos dias, por favor me podrian ayudar tengo una impresora fiscal bixolon y por motivos ajenos tube que cerrar la razon social y me dedique a otro ramo ahora necesito cambiarle el nombre a mi impresora fiscal para poder trabajar facturando, esta en buen estado y de poco uso ya que el negocio no fue rentable puedo hacer eso y como lo hago y me pueden ayudar
