### ISSUE TITLE
connection problem with openerp server http://host:8069/ can't complete database list call

### ISSUE THREAD

**Issue by Danisan** [csrocha/fpoc-chrome#8]
Esta excepción es manifestada en el acto de presionar el botón "connect".

Configuración de Odoo (8): docker con módulos fpoc instalados (3 modulos). y puerto 8069 expuesto a la red publica a través del host, que es un Ubuntu 14.04 con docker 1.8.

Los módulos de fpoc no dieron error al ser instalados.

La prueba de acceso es hecha desde red pública en forma remota (internet, no LAN). El servidor funciona bien (aunque un poco lento, lo cual me hacía sospechar de un timeout).

El controlador/impresora no está conectado, pero la intención es probar la conectividad por ws.

La misma extensión de Chrome, utilizada con un localhost y la misma base de datos funciona bien.

Este es el log en el servidor cuando se presiona el botón connect (es decir, que algún tipo de conectividad hay):

2015-10-30 22:47:49,512 1 ERROR None openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1413, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1430, in match
    raise NotFound()
NotFound: 404: Not Found
2015-10-30 22:47:49,514 1 INFO None werkzeug: 179.8.165.221 - - [30/Oct/2015 22:47:49] "GET //web/database/get_list?jsonp=_&id=p1&r=%7B%22params%22%3A%7B%7D%7D HTTP/1.1" 200 -

Si entro por navegador a web/database/selector las bases las entrega bien, y por lo que veo, la respuesta del werkzeug es exactament ela misma en ambos casos, pero en este último, no remata con la excepción mostrada:

2015-10-30 22:49:57,245 1 INFO None werkzeug: 179.8.165.221 - - [30/Oct/2015 22:49:57] "GET //web/database/get_list?jsonp=_&id=p1&r=%7B%22params%22%3A%7B%7D%7D HTTP/1.1" 200 -

**Comment by csrocha** [comment]
@Danisan , podrías realizar la siguiente prueba? Acceder a:

(http://host:8069/web/database/get_list?jsonp=_&id=p1)

si te da algún error? Cambia **host** por tu host.

**Comment by Danisan** [comment]
Ahi no da ningún error entrega un json:

_({"jsonrpc": "2.0", "id": null, "session_id": "12345.....", "result": ["bd1", "bd2"]});

**Comment by csrocha** [comment]
Ok. El servidor anda bien, lo que anda mal es el cliente. Veo de resolver el problema.

**Comment by csrocha** [comment]
@Danisan fijate si el problema es que la url que ingresas termina con la barra invertida:

http://host:8069/

Si es así, prueba de la siguiente manera:

http://host:8069

o sea, sin la barra invertida.

**Comment by momo06** [comment]
Hi.

> @Danisan , podrías realizar la siguiente prueba? Acceder a:
> 
> (http://host:8069/web/database/get_list?jsonp=_&id=p1)
> 
> si te da algún error? Cambia **host** por tu host.

I have the same error.
http://host:8069/web/database/get_list?jsonp=_&id=p1 doesn t work for me (replacing host by my local host).  It gave me 404 response. What is wrongly configure on my server? (synology nas runing Odoo throught docker).
I can use Odoo normally locally o from outside
Thanks
